### ISSUE TITLE
fancyhdr errors if expl3 debug options are enabled

### ISSUE THREAD

**Issue by u-fischer** [pietvo/fancyhdr#20]
~~~~
\ExplSyntaxOn
\debug_on:n { check-declarations , deprecation }
\ExplSyntaxOff
\documentclass[11pt]{article}
\usepackage{fancyhdr}
\pagestyle{fancy}
\makeatletter\ExplSyntaxOn
%\def\f@nch@clear@par@hook:n#1{}
\ExplSyntaxOff
\begin{document}
blub
\end{document}
~~~~

errors with

~~~~
! LaTeX Error: Inconsistent local/global assignment

For immediate help type H <return>.
~~~~

I do not think that fancyhdr should redefine internal LaTeX hook commands in `\def\f@nch@clear@par@hook:n` to clear the hooks locally (and for hyperref as suggested in issue #18 it is also not needed, that problem should and was fixed in hyperref). fancyhdr can not know if a user wants code in a para hook (or in other hooks) to be executed in the header and footer and so removing the hook code unconditionally is in my opinion to drastic. E.g. currently we tag header and footer as artifacts, but in case that we want to resume tagging e.g. for an address in the header on the first page we would need working hooks.
Instead there should be imho some conditional that allows user and package authors to check in the hook code if they are in a header or footer.  I would suggest that you open an issue at the LaTeX2e github, so that one can agree about how to name and implement such a conditional.

**Comment by pietvo** [comment]
Hi Ulrike,
Although you have solved the problem with the LaTeX kernel theorems, the original problem that was reported in https://tex.stackexchange.com/q/691262/113546 used the package `thmtools` and there it hasn't been solved yet.

Anyway, I think `fancyhdr` should start with a state that is as clean as possible, i.e. all catcodes reset to their defaults, `\everypar` empty, no paragraph hooks intruding from the main text (certainly no `Next` hooks), etc.
I agree that the code to do this is far from ideal. In fact I included this code with pain in my heart, but as long as the LaTeX kernel doesn't provide proper tools for this, I have no choice. I discussed this with Frank in issue https://github.com/pietvo/fancyhdr/issues/18.

And I agree that there should be a distinction between paragraph hooks meant for the main text, and those meant to be used inside `fancyhdr`. But with the hooks I introduced in `fancyhdr` version 4.5, it is possible to add a `fancyhdr` hook that sets up a paragraph hook to be used inside the `fancyhdr` processing. I think this is cleaner than checking if you are in a header or footer, although such a test may be useful anyway.

**Comment by u-fischer** [comment]
I think that fancyhdr is the wrong place to handle this. We end up with different behaviour depending on if fancyhdr or scrlayer or the standard headers are used and you are asking people and package writer to write conditional code for all these packages.  Whatever should be done here, should be done in a way that it works for all headers and footers and without packages changing LaTeX internals.  

> I have no choice.

Sure you have a choice ;-). That the anchor is wrong with thmtools, is a bug of hyperref and thmtools. The patch used to get the anchor into the right place is simply bad and you do not have to fix that by adding another dubious hack. If that is the only reason for your patch than you can remove it. I will take a new look at that.

If you know of other problems with the para hooks in the header then please open an issue at our github.

**Comment by pietvo** [comment]
Hello Ulrike,
I understand your concerns, and I agree that this is not the ideal solution. So I hope we can find a better way.

First, the problem is bigger than the bug in `thmtools/hyperref`. There are a lot of situation where a paragraph hook (and probably also other hooks) should not be applied in the headers and footers. I think in most cases it is undesirable, unless the author specifically intends it.

For example if the author wants to number the paragraphs in the text body, it could be done in this way:
```
\newcounter{para}
\AddToHook{para/begin}{%
  \stepcounter{para}
  \fbox{\thepara}
}
```

It is very probable that this author wants their paragraphs in the text body to be consecutively numbered, and not the header and footer fields.
The problem gets worse if a `Next` hook is used. Then you don't want the hook to be executed accidentally in the header instead of the next paragraph in the text, just because TeX decides to run the page builder before the next paragraph is processed.

That said, I agree with you that it isn't a `fancyhdr` specific problem. In fact it goes beyond headers and footers, because it could also play a role in shipout hooks. So there should be a way to differentiate between normal text and processing during the page builder.

I am not so sure that a conditional to check if we are in the page builder is the proper solution. I think this could work, but it is not nice if an author must be constantly aware that this test should be applied. For example, if the hooks are declared in a package, the author of the package doesn't know if the user of the package also used `fancyhdr` or any other header/footer layout solution, or a shipout hook that uses paragraphs, or whatever. So from a user point of view  it seems better to me if the default would be that hooks defined in the main document are not processed during the page builder, and that special syntax is required if they must be processed during the page builder. But I don't know if this is feasible.

For now I am changing the code a bit so that it will be possible to add the hooks in the headers and footers, e.g. with
```
\AddToHook{fancyhdr/before}{%
  \AddToHook{para/begin}{XXXX}
}
```
Please note that all the processing to switch of the hooks inside `fancyhdr` does not influence the processing in the main document because it is local in a TeX group. It **is** unfortunate that this only can be done by fiddling with the kernel internals, which obviously in general is a bad way to do things, but as long as there is no better way, this is how it is.

I am open for any suggestions, in addition to what you have written above. I will be happy if we can solve this in a proper way. For now, I will keep the currect solution or something similar. I hope that in a future release this will be resolved completely.

**Comment by u-fischer** [comment]
> does not influence the processing in the main document because it is local in a TeX group

The issue came up because various tests in the tagpdf testsuite broke as you change global variables locally.  And any document that uses `\debug_on:n { check-declarations , deprecation }` to check the sanity of its code will error too. 
I'm currently working around that by disabling your internal command but this naturally means that I no longer really test fancyhdr but a modified version.

> For now, I will keep the currect solution or something similar. 
> So I hope we can find a better way.
> I hope that in a future release this will be resolved completely.

Then please put a date on your work-around and disable it again at the next LaTeX release.  And push us to do something about it until then by opening an issue and showing examples of the problems to resolve.

**Comment by pietvo** [comment]
I have changed the code now to no longer change global variables locally, also to avoid filling up the save stack. I now save the variables in local variables, reset them globally, and at the end of the header/footer restore them globally to the saved value. So this should solve that problem, I hope.

**Comment by u-fischer** [comment]
> Sorry, I don't understand what would be different in the next LaTeX release.

I only meant that you should add a deadline to avoid that the patch stays there for a long time. I have learned that temporary patches can have a long life if there is no pressure to remove them again.

**Comment by u-fischer** [comment]
Your new code in `2025/01/06 v5.1` does not resolve the declaration errors. The only thing that changed is that I have to disable a different command to avoid the errors.

~~~~
\ExplSyntaxOn
\debug_on:n { check-declarations , deprecation }
\ExplSyntaxOff
\documentclass{article}
\usepackage{fancyhdr}
\makeatletter\ExplSyntaxOn
%Avoid fancyhdr killing of para hooks:
%\def\f@nch@restore@parhook#1{} %<------- needed
%\def\f@nch@saveclr@parhook#1{}
\makeatother\ExplSyntaxOff
\pagestyle{fancy}
\lhead{some \emph{text} }
\lfoot{some \emph{text} }
\begin{document}
\section{some text}
\subsection{blub}
\end{document}
~~~~

~~~~
! LaTeX Error: Inconsistent local/global assignment

For immediate help type H <return>.
 ...                                              
                                                  
l.48 \end{document}
                   
? H

This is a coding error.

Global assignment to a constant variable '\__hook para/before'.

? x
~~~~

**Comment by pietvo** [comment]
Yes, unfortunately I discovered this too late. I forgot to run your test document. I feel very embarrassed to give you this trouble. This whole thing makes me a bit depressed.

I have submitted a new version, 5.1.1. It should appear on CTAN today.
I hope you can bear with me.
